In [2]:
import numpy as np 

#Tablica zawierająca 10 zer
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#Tablica zawierająca 10 piątek
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [4]:
#Tablica zawierająca liczby 10 - 50
np.arange(10,51,1) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
#macierz jednostkowa o wymiarach 3x3
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
#macierz o wymiarach 5x5 zawierającą liczby z dystrybucji normalnej (Gaussa)
np.random.randn(5,5)

array([[ 1.17125029, -0.59926336, -2.40142551, -0.87629436, -1.65539466],
       [-0.55526734, -0.15428781,  0.52253149, -0.63145986,  1.48521834],
       [-1.96158466,  1.06479288, -0.02049088, -2.28695964,  1.54281371],
       [-1.18237443, -0.65656816,  0.64809006,  0.16661887,  0.59086537],
       [-1.31057876, -1.12676075,  0.56724533, -0.56775395, -0.41952487]])

In [13]:
#utwórz macierz o wymiarach 10x10 zawierającą od 0,01 do 1 z krokiem 0,01
np.arange(0.01,1.01, 0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [19]:
#tablica zawierająca 20 liniowo rozłożonych liczb między 0 a 1 (włącznie z 0 i 1),
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [36]:
#utwórz tablicę zawierającą losowe liczby z przedziału (1, 25), 
#następnie zamień ją na macierz o wymiarach 5 x 5 z tymi samymi liczbami:
a = np.random.randint(24, size=(5,5))+1
##oblicz sumę wszystkich liczb w ww. macierzy,
a.sum()
##oblicz średnią wszystkich liczb w ww. macierzy,
a.mean()
##oblicz standardową dewiację dla liczb w ww. macierzy,
np.std(a)
a


array([[25,  2,  8, 21, 24],
       [ 3,  3, 18,  9, 14],
       [11,  9,  3, 20, 21],
       [15, 20, 22, 16, 11],
       [ 1, 21, 25, 20, 14]])

In [37]:
##oblicz sumę każdej kolumny ww. macierzy i zapisz ją do tablicy,
b=a.sum(0)
b

array([55, 55, 76, 86, 84])

In [44]:
#utwórz macierz o wymiarach 5x5 zawierającą losowe liczby z prz. (0, 100) i:
c = np.random.randint(101, size=(5,5))
c

array([[87, 52, 61, 54, 30],
       [84, 30,  7, 98, 29],
       [57, 60, 43, 29, 92],
       [49, 28, 74, 59, 13],
       [ 0, 31, 79, 97, 97]])

In [48]:
#oblicz medianę tych liczb
np.median(c)

54.0

In [49]:
#znajdź najmniejszą liczbę tej macierzy,
np.min(c)

0

In [50]:
#znajdź największą liczbę tej macierzy,
np.max(c)

98

In [59]:
#utwórz macierz o wymiarach różnych od siebie i większych od 1, 
#zawierającą losowe liczby z przedziału (0, 100) i dokonaj jej transpozycji
np.random.randint(101, size=(2,5)).T

array([[ 71,  61],
       [ 35,  87],
       [ 10,  69],
       [100,  65],
       [ 39,  55]])

In [62]:
#utwórz dwie macierze o odpowiednich wymiarach (doczytać), 
#większych od 2 i dodaj je do siebie,

x = np.random.randint(10, size=(2,5))
x


array([[3, 0, 0, 0, 6],
       [4, 4, 8, 4, 2]])

In [63]:
y = np.random.randint(10, size=(2,5))
y


array([[6, 6, 3, 3, 4],
       [0, 4, 8, 2, 5]])

In [64]:
x+y

array([[ 9,  6,  3,  3, 10],
       [ 4,  8, 16,  6,  7]])

In [69]:
#utwórz dwie macierze o odpowiednich wymiarach (doczytać) różńych od siebie, 
#większych od 2 i pomnóż je przez siebie,
x = np.random.randint(10, size=(2,5))
y = np.random.randint(10, size=(5,2))
np.matmul(x,y)


array([[51, 53],
       [77, 97]])